### PR TITLE
Support readable stream

### PR DESCRIPTION
**Pull request by m77so**
I'd like to use readable stream directly for discord bot.

Usage: https://github.com/m77so/discord-alice/blob/c7d5d7c50e54596ad6c68f337493ba125f7aad00/src/niconico.ts

### CODE REVIEW

**Comment by uetchy** [comment]
Thank you for the patch!
I tried to test your PR on my machine but ended up seeing 403 error.
Are you sure that you can successfully download a video?

**Comment by m77so** [comment]
Yes, it works on my local machine and GCP cloud shell.

This is my test execution on GCP cloud shell.
```
myemailaddress@cloudshell:~ (testprj)$ git clone https://github.com/m77so/niconico.git
Cloning into 'niconico'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 924 (delta 0), reused 2 (delta 0), pack-reused 918
Receiving objects: 100% (924/924), 856.45 KiB | 778.00 KiB/s, done.
Resolving deltas: 100% (609/609), done.
myemailaddress@cloudshell:~ (testprj)$ cd niconico/
myemailaddress@cloudshell:~/niconico (testprj)$ yarn
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 17.04s.
myemailaddress@cloudshell:~/niconico (testprj)$ NICONICO_EMAIL=example@example.com NICONICO_PASSWORD=hogehoge yarn test
yarn run v1.22.4
$ jest --coverage
(node:1268) ExperimentalWarning: The fs.promises API is experimental
 PASS  tests/nicovideo.test.ts (33.043s)
 PASS  tests/niconico.test.ts
--------------|---------|----------|---------|---------|-------------------
File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
--------------|---------|----------|---------|---------|-------------------
All files     |   98.18 |     87.5 |     100 |   98.15 |                  
 niconico.ts  |     100 |      100 |     100 |     100 |                  
 nicovideo.ts |   97.62 |    83.33 |     100 |   97.56 | 42               
--------------|---------|----------|---------|---------|-------------------

Test Suites: 2 passed, 2 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        34.556s
Ran all test suites.
Done in 35.44s.
myemailaddress@cloudshell:~/niconico (testprj)$ ls
coverage  examples        LICENSE       package.json  src    tsconfig.json  yarn.lock
docs      jest.config.js  node_modules  README.md     tests  tslint.json    【ゆめにっき】クリプト・オブ･ザ・モノクロダンサー.mp4
myemailaddress@cloudshell:~/niconico (testprj)$ node -v
v10.14.2

```

**Comment by uetchy** [comment]
Merged🚀

**Comment by uetchy** [comment]
@m77so Could you add a document for `stream` in README?

**Comment by m77so** [comment]
Sure, I added a document on #114 .

**Pull request merged**
